# Generated by Django 3.2.9 on 2021-11-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('judul', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=150)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
